=== joshmarinacci/idealos_schema_tools/apps-schema.json
{
  "$id": "https://josh.earth/idealos/apps-schema.json",
  "$schema": "http://json-schema.org/draft-06/schema#",
  "title": "AppList",
  "type": "object",
  "required": ["system","user"],
  "properties": {
    "starter": {
      "$ref": "https://josh.earth/idealos/app-schema.json"
    },
    "system": {
      "type": "array",
      "description": "list of system level apps that are secure",
      "items": {
        "$ref": "https://josh.earth/idealos/app-schema.json"
      }
    },
    "user": {
      "type": "array",
      "description": "list of user level apps that are insecure",
      "items": {
        "$ref": "https://josh.earth/idealos/app-schema.json"
      }
    },
    "services": {
      "type": "array",
      "description": "list of headless services that are alwayw running",
      "items": {
        "$ref": "https://josh.earth/idealos/app-schema.json"
      }
    },
    "menu-plugins": {
      "type": "array",
      "description": "list of apps that go into the menu",
      "items": {
        "$ref": "https://josh.earth/idealos/app-schema.json"
      }
    },
    "sidebar-plugins": {
      "type": "array",
      "description": "list of apps that go into the sidebar",
      "items": {
        "$ref": "https://josh.earth/idealos/app-schema.json"
      }
    }
  }
}

=== joshmarinacci/idealos_schema_tools/apps.json
{
  "system": [
    {
      "name": "menbuar",
      "entrypoint": "apps/menubar.js",
      "groups": ["secure","menubar"]
    },
    {
      "name": "sidebar",
      "entrypoint": "apps/sidebar.js",
      "groups": [ "sidebar", "secure"]
    },
    {
      "name": "dock",
      "entrypoint": "apps/dock.js",
      "groups": [ "dock,", "secure"]
    }
  ],
  "user": [
    {
      "name": "fractal",
      "title": "Fractal App",
      "icon": "mandlebrot",
      "entrypoint": "apps/fractal.js"
    },
    {
      "name": "guitest",
      "title": "Cool Gui Tester",
      "icon": "guitester",
      "entrypoint": "apps/gui_test.js"
    }
  ],
  "services": [
    {
      "name": "volume-overlay",
      "title": "volume overlay",
      "entrypoint": "apps/overlay/volume.js"
    }
  ],
  "menu-plugins": [
    {
      "name": "battery-viewer",
      "title": "battery viewer",
      "entrypoint": "apps/menu/battery.js"
    },
    {
      "name": "network-viewer",
      "title": "network viewer",
      "entrypoint": "apps/menu/wifi.js"
    },
    {
      "name": "search-launcher",
      "title": "search launcher",
      "entrypoint": "apps/menu/search.js"
    }
  ],
  "sidebar-plugins": []
}
